version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: funnypenny-server:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/funnypenny
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: funnypenny
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: funnypenny
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: